// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPMokIyla_ZHiMUxmIdkdQaGR-luQUtFU',
    appId: '1:392358148104:web:bab90cc49ea8d99f0079bd',
    messagingSenderId: '392358148104',
    projectId: 'my-address-7c531',
    authDomain: 'my-address-7c531.firebaseapp.com',
    storageBucket: 'my-address-7c531.appspot.com',
    measurementId: 'G-FNNLTP54WK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPg58DeEh9lbl8Wt5RZzhoucxTt8fcaJs',
    appId: '1:392358148104:android:1ec35e29da763bad0079bd',
    messagingSenderId: '392358148104',
    projectId: 'my-address-7c531',
    storageBucket: 'my-address-7c531.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYw2ZVadrWlCV8kA9GYgnMaKp5XOaCGXM',
    appId: '1:392358148104:ios:727eed51eb0ff89e0079bd',
    messagingSenderId: '392358148104',
    projectId: 'my-address-7c531',
    storageBucket: 'my-address-7c531.appspot.com',
    iosClientId: '392358148104-ibu579baid8i7sgc4ie0fmn0gjdta65t.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFlutterKonsi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYw2ZVadrWlCV8kA9GYgnMaKp5XOaCGXM',
    appId: '1:392358148104:ios:727eed51eb0ff89e0079bd',
    messagingSenderId: '392358148104',
    projectId: 'my-address-7c531',
    storageBucket: 'my-address-7c531.appspot.com',
    iosClientId: '392358148104-ibu579baid8i7sgc4ie0fmn0gjdta65t.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFlutterKonsi',
  );
}
